### ISSUE TITLE
CHANGE: Increase MAXPLAYERITEMS for civic structures to 1000 items

### ISSUE THREAD

**Issue by stacy19201325** [TarkinII/Core3#2]
Tatooine theater only allowed me to drop 400 items in it.  (This was a houseplop generated theater, if that matters).  The status shows 400 items allowed, but this is supposedly because of a client side string file and should still be allowed to drop more than that, but I got "This house has too many items" at attempting to drop a 401st item.

**Comment by stacy19201325** [comment]
This was in the testing document, but I'm not able to find any such commit in Kinshi's Core3 repo.

**Comment by kinshi** [comment]
This is not a LUA update, but a C++ edit. (so no need to edit lots of files)

Fortunately it is a single edit, but does require an updated server binary.

**Comment by Tatwi** [comment]
ALL house plop items use the same function, 

StructureObject* structureObject = StructureManager::instance()->placeStructure(creature, templateString, x, y, angle, persistenceLevel);

As called from 

+int DirectorManager::adminPlaceStructure(lua_State* L) 

The placeStructure() function is not the same as the placeStructureFromDeed() function. It has fewer rules and in the context of the house plop command, it was intended for use a an admin tool, rather than live server content creation device. As such, ALL buildings placed using it are treated exactly the same as player houses. As such, if the lua template for the building does not have a lots = # value then the default value will be used. By default, NPC structures do not have a lots = # value. 

This is working as designed. If you want different values for NPC style structures, add a lots = # to their lua templates.

**Comment by stacy19201325** [comment]
Fixed.
